### ISSUE TITLE
Write clean docs

### ISSUE THREAD

**Issue by jaamaalxyz** [sjsakib/unsplash-dbg#1]
Write clean docs, without docs how can we know your great idea to use brother. 😄  🚀 💯

**Comment by sjsakib** [comment]
I will, bro. For now, I'm just saving the code here. In fact, I have plans to make a GUI for it.

**Comment by jaamaalxyz** [comment]
It's just a friendly reminder 😄 , I know you are an enthusiast and organize person at all. looking forward to seeing your GUI soon...

**Comment by sjsakib** [comment]
Thanks for the support bro :heart:
